# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "

[golang]
format = "using [$symbol$version]($style) "

[nodejs]
format = "using [$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "📦 "